-- create
CREATE TABLE STUDENTS (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO STUDENTS VALUES (0001, 'Clark', 16, Moscow);
INSERT INTO STUDENTS VALUES (0002, 'Dave', 18, Voronezh);
INSERT INTO STUDENTS VALUES (0003, 'Ava', 19, Kaliningrad);
INSERT INTO STUDENTS VALUES (0004, 'John', 17, Moscow);
INSERT INTO STUDENTS VALUES (0005, 'Roman', 18, Moscow);
INSERT INTO STUDENTS VALUES (0006, 'Fedor', 16, Tula);